CONFIG = {
    "SYMBOL": "NIFTY",
    "LOT_SIZE": 50,
    "INITIAL_CAPITAL": 100000.0,
    "RISK_REWARD_RATIO": 2.0,
    "MIN_AI_CONFIDENCE": 0.70,
    "MODEL_FILE": "nifty_ai_model.pkl",
    "TELEGRAM_BOT_TOKEN": "YOUR_BOT_TOKEN",
    "TELEGRAM_CHAT_ID": "YOUR_CHAT_ID",
    "ANGEL_API_KEY": "ENvuvGju",
    "ANGEL_CLIENT_CODE": "B130919",
    "ANGEL_PASSWORD": "2727",
    "ANGEL_TOTP_TOKEN": "7H7EQMOW6JFK2OPXWZYGY7UCOA"
}
